# **Диагностическая работа по библиотеке NumPy**

#### **Задание 1: Векторизация в NumPy**


Напишите функцию, которая принимает два массива: одномерный массив `x` длины `n` и двумерный массив `A` размера `m×n`. Функция должна вычислить выражение `A @ x - 1` (матричное произведение A на x, затем вычитание 1 из каждого элемента результата и применение экспоненты) без использования циклов Python. Продемонстрируйте, насколько этот подход быстрее, чем решение с использованием циклов.

In [14]:
import numpy as np
import time
import math


def vectorized_compute(A, x):
    return np.exp(A @ x - 1)

def loop_compute(A, x):
    m, n = len(A), len(A[0])
    
    result = [0] * m
    for i in range(m):
        sum_ax = 0
        for j in range(n):
            sum_ax += A[i][j] * x[j]
        result[i] = sum_ax

    for i in range(m):
        result[i] = math.exp(result[i] - 1)
    return result


def cm_performance(m=1000, n=1000):

    np.random.seed(42)
    A = np.random.rand(m, n)
    x = np.random.rand(n)
    

    A_list = A.tolist()
    x_list = x.tolist()
    

    start_time = time.time()
    result_vectorized = vectorized_compute(A, x)
    vectorized_time = time.time() - start_time
    

    start_time = time.time()
    result_loop = loop_compute(A_list, x_list)
    loop_time = time.time() - start_time
    

    result_loop = np.array(result_loop)
    is_close = np.allclose(result_vectorized, result_loop, rtol=1e-5, atol=1e-8)
    
    print(f"Размер A: {m}x{n}, размер x: {n}")
    print(f"Время векторизация: {vectorized_time:.6f} сек")
    print(f"Время циклы: {loop_time:.6f} сек")
    print(f"Ускорение: {loop_time / vectorized_time:.2f}x")
    print(f"Результаты совпадают: {is_close}")


cm_performance()

Размер A: 1000x1000, размер x: 1000
Время векторизация: 0.001007 сек
Время циклы: 0.126152 сек
Ускорение: 125.27x
Результаты совпадают: True


#### **Задание 2: Индексация и маски**


Дан двумерный массив `data` с числовыми данными. Выполните следующие операции:
1. Создайте маску для всех элементов массива, которые больше среднего значения массива.
2. Замените все элементы, соответствующие этой маске, на их квадратные корни.
3. Остальные элементы замените на их квадраты.
4. Подсчитайте количество элементов, которые были заменены на квадратные корни.

In [2]:
np.random.seed()
data = np.random.randint(-10, 10, size=(4, 4))

mean_value = np.mean(data)
mask = data > mean_value
data[mask] = np.sqrt(data[mask])
data[~mask] = data[~mask] ** 2
count_replaced = np.sum(mask)

print("Массив:\n", data)
print("элементы:", count_replaced)

Массив:
 [[ 2  3 64  3]
 [81 25  1 81]
 [25  1  2  1]
 [ 2  1 49  2]]
элементы: 7


#### **Задание 3. Структурированные массивы и группировка**


Создайте структурированный массив, представляющий информацию о студентах с полями: 'имя' (строка), 'возраст' (целое число) и 'оценки' (массив из 3 чисел с плавающей точкой). Выполните следующие операции:
1. Добавьте 10 студентов с разными данными.
2. Вычислите средний балл для каждого студента и добавьте это значение в новое поле 'средний_балл'.
3. Сгруппируйте студентов по возрасту и для каждой возрастной группы вычислите средний балл по всем предметам.
4. Отсортируйте студентов по убыванию среднего балла.

In [4]:
import numpy as np


dtype = [('name', 'U20'), ('age', int), ('grades', float, 3), ('avg_grade', float)]
students = np.zeros(10, dtype=dtype)
print(students)

students['name'] = ['name 1', 'name 2', 'name 3', 'name 4', 'name 5',
                   'name 6', 'name 7', 'name 8', 'name 9', 'name 10']
students['age'] = [18, 19, 18, 20, 19, 18, 20, 19, 18, 20]
students['grades'] = [
    [85.5, 90.0, 88.5], [78.0, 82.5, 80.0], [92.0, 95.0, 90.0],
    [70.0, 75.0, 72.5], [88.0, 85.0, 87.0], [90.0, 92.5, 91.0],
    [65.0, 70.0, 68.0], [82.0, 80.0, 81.5], [95.0, 93.0, 94.0],
    [77.0, 79.0, 78.0]
]


students['avg_grade'] = np.mean(students['grades'], axis=1)


ages = np.unique(students['age'])
age_group_means = []
for age in ages:
    mask = students['age'] == age
    mean_grade = np.mean(students['avg_grade'][mask])
    age_group_means.append((age, mean_grade))

sorted_students = np.sort(students, order='avg_grade')[::-1]

print("Данные о студентах:")
for student in sorted_students:
    print(f"Имя: {student['name']}, Возраст: {student['age']}, "
          f"Оценки: {student['grades']}, Средний балл: {student['avg_grade']}")

print("\nСредний балл по возрастным группам:")
for age, mean_grade in age_group_means:
    print(f"Возраст: {age}, Средний балл: {mean_grade}")

[('', 0, [0., 0., 0.], 0.) ('', 0, [0., 0., 0.], 0.)
 ('', 0, [0., 0., 0.], 0.) ('', 0, [0., 0., 0.], 0.)
 ('', 0, [0., 0., 0.], 0.) ('', 0, [0., 0., 0.], 0.)
 ('', 0, [0., 0., 0.], 0.) ('', 0, [0., 0., 0.], 0.)
 ('', 0, [0., 0., 0.], 0.) ('', 0, [0., 0., 0.], 0.)]
Данные о студентах:
Имя: name 9, Возраст: 18, Оценки: [95. 93. 94.], Средний балл: 94.0
Имя: name 3, Возраст: 18, Оценки: [92. 95. 90.], Средний балл: 92.33333333333333
Имя: name 6, Возраст: 18, Оценки: [90.  92.5 91. ], Средний балл: 91.16666666666667
Имя: name 1, Возраст: 18, Оценки: [85.5 90.  88.5], Средний балл: 88.0
Имя: name 5, Возраст: 19, Оценки: [88. 85. 87.], Средний балл: 86.66666666666667
Имя: name 8, Возраст: 19, Оценки: [82.  80.  81.5], Средний балл: 81.16666666666667
Имя: name 2, Возраст: 19, Оценки: [78.  82.5 80. ], Средний балл: 80.16666666666667
Имя: name 10, Возраст: 20, Оценки: [77. 79. 78.], Средний балл: 78.0
Имя: name 4, Возраст: 20, Оценки: [70.  75.  72.5], Средний балл: 72.5
Имя: name 7, Возраст:

#### **Задание 4. Преобразование и изменение формы массивов**

Дан одномерный массив `data` длины `n*m`, где `n` и `m` - целые числа. Выполните следующие операции:
1. Преобразуйте его в двумерный массив размера `n×m`.
2. Транспонируйте полученный массив.
3. Примените функцию `np.where` для замены всех отрицательных значений на их абсолютные значения, а положительных значений на их квадратные корни.
4. Вычислите сумму элементов по каждой строке и столбцу. Определите строку с максимальной суммой и столбец с минимальной суммой.

In [5]:
import numpy as np

n, m = 4, 3
data = np.array([-1, 4, -9, 16, -25, 36, -49, 64, -81, 100, -121, 144])

matrix = data.reshape(n, m)
print("1.Двумерный массив:\n", matrix)

transposed = matrix.T
print("\n2.Транспонированный массив:\n", transposed)

transformed = np.where(matrix < 0, np.abs(matrix), np.sqrt(matrix))
print("\n3.Преобразованный массив:\n", transformed)

row_sums = np.sum(transformed, axis=1)
col_sums = np.sum(transformed, axis=0)
print("\n4.Суммы по строкам:", row_sums)
print("4.Суммы по столбцам:", col_sums)

max_row_idx = np.argmax(row_sums)
min_col_idx = np.argmin(col_sums)
print(f"\n4.Строка с максимальной суммой (индекс {max_row_idx}): {row_sums[max_row_idx]:.2f}")
print(f"4.Столбец с минимальной суммой (индекс {min_col_idx}): {col_sums[min_col_idx]:.2f}")

1.Двумерный массив:
 [[  -1    4   -9]
 [  16  -25   36]
 [ -49   64  -81]
 [ 100 -121  144]]

2.Транспонированный массив:
 [[  -1   16  -49  100]
 [   4  -25   64 -121]
 [  -9   36  -81  144]]

3.Преобразованный массив:
 [[  1.   2.   9.]
 [  4.  25.   6.]
 [ 49.   8.  81.]
 [ 10. 121.  12.]]

4.Суммы по строкам: [ 12.  35. 138. 143.]
4.Суммы по столбцам: [ 64. 156. 108.]

4.Строка с максимальной суммой (индекс 3): 143.00
4.Столбец с минимальной суммой (индекс 0): 64.00


C:\Users\Owl\AppData\Local\Temp\ipykernel_11376\1874073306.py:12: RuntimeWarning: invalid value encountered in sqrt
  transformed = np.where(matrix < 0, np.abs(matrix), np.sqrt(matrix))


#### **Задание 5. Оптимизация памяти и продвинутые операции**










Напишите функцию, которая генерирует матрицу размера `10000×10000`, заполненную случайными числами от 0 до 1, но использует минимально возможное количество памяти. Затем выполните следующие операции:
1. Не создавая копии матрицы, вычислите её определитель (если возможно) или оценку определителя.
2. Используя технику "memory views" или "strided arrays", извлеките каждый 10-й элемент по диагонали матрицы.
3. Создайте представление матрицы как трёхмерного массива размера `100×100×100` без копирования данных.
4. Продемонстрируйте, как можно применить batch-операцию (например, нормализацию) к каждому "срезу" этого трёхмерного представления.

Эти задания проверяют понимание ключевых возможностей NumPy, таких как векторизация вычислений, продвинутая индексация, работа с многомерными массивами, и оптимизация памяти

In [6]:
import numpy as np
matrix = np.random.rand(1000, 1000).astype('float32')

determinant = np.linalg.det(matrix)

print("1. Определитель:", determinant)
diagonal_elements = matrix.diagonal()[::10]
print("\n2. Каждый 10 элемент по диагонали", diagonal_elements)
matrixNew = matrix.reshape((100, 100, 100))
print("\n3. Массив 100*100*100", matrixNew)
normalized_slices = (matrixNew - np.mean(matrixNew, axis=(1, 2), keepdims=True)) / np.std(matrixNew, axis=(1, 2), keepdims=True)
print("\n4. Первый срез после нормализации:\n", normalized_slices[0])

1. Определитель: -inf

2. Каждый 10 элемент по диагонали [0.6454176  0.9060418  0.01784705 0.04135577 0.9031037  0.63250935
 0.0187242  0.20878018 0.64367974 0.17021364 0.3227769  0.80592614
 0.46001884 0.3708468  0.54175115 0.66787565 0.8039595  0.03894476
 0.5139667  0.08800232 0.30396613 0.17199191 0.8670831  0.6820109
 0.85824615 0.6243007  0.23394515 0.18521543 0.459896   0.16264343
 0.721599   0.56225204 0.6132077  0.7691082  0.9777649  0.38950238
 0.02952871 0.36222485 0.39129266 0.21908654 0.15373734 0.14301814
 0.27672207 0.04623875 0.12245075 0.9390397  0.78085774 0.63259923
 0.8875379  0.18570815 0.36804312 0.03781869 0.9506855  0.5428326
 0.85582316 0.7513908  0.18001948 0.08708689 0.00138833 0.9126365
 0.50844    0.15610409 0.06050027 0.981876   0.8483932  0.816461
 0.79514575 0.7120259  0.64149714 0.41805905 0.8164605  0.2820371
 0.5698304  0.0869489  0.11502831 0.9268711  0.36162892 0.9358174
 0.41795808 0.4945552  0.0934752  0.61006695 0.85571676 0.7710706
 0.9942828  0

c:\Users\Owl\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\linalg\linalg.py:2180: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)
